import json
import os
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from openai import OpenAI

from database import ensure_indexes, get_database, get_gridfs, utc_now
from ingest import ingest_pdf
from models import ChatRequest, ChatResponse, HealthResponse
from retrieval import get_all_tickers_and_quarters, retrieve_chunk_documents, retrieve_relevant_chunks

load_dotenv()

SYSTEM_PROMPT = """
You are an elite financial research assistant for Indian stock market investors on the SIHL platform.

You have TWO modes of answering. Always choose the most appropriate one based on the user's question.

=========================================
MODE 1: DIRECT Q&A (Specific Questions)
=========================================
Use this mode if the user asks a specific, narrow question (e.g., "What is the PAT?", "Compare revenue across quarters", "What are the risks?", "Who are the competitors?").
- Answer ONLY the specific question asked. Do not generate a full report.
- Begin your response with an accurate Sentiment (e.g., "**Sentiment:** Bullish") based on the data you find. DO NOT default to Neutral.
- If numeric data is relevant, ALWAYS present it in a clean Markdown table. Create dynamic columns based on the exact data you find.
- Base your answers strictly on the retrieved report chunks.
- DO NOT use the "#### Financial Performance" heading or the massive report template.

=========================================
MODE 2: FULL REPORT GENERATION
=========================================
Use this mode ONLY if the user asks for a summary, a full report, earnings analysis, or a general overview (e.g., "Summarize Q3 2025 earnings", "Give me a report").

Respond in EXACTLY this format (do not omit any sections):

➤ [COMPANY_TICKER] – [Report Type] Report ([QuarterYear])

**Sentiment**
[Single word: Bullish / Bearish / Neutral - Ensure this accurately reflects the data!]

**Positive Highlights**
- [concise point, max 15 words]
- [concise point, max 15 words]
- [concise point, max 15 words]

**Negative Highlights**
- [concise point, max 15 words]
- [concise point, max 15 words]

**Summary**
### Company Financial Report

#### Financial Performance
[Create a Markdown table here. DYNAMICALLY generate the columns based on the exact quarters and metrics available in the text. DO NOT leave columns empty. If you only have one quarter of data, only use one column. Include a 'Comments' column at the end.]

#### Operational Highlights
- [bullet points covering volumes, capacity, key segments]

#### Risks and Challenges
- [bullet points]

#### Outlook
- [bullet points on growth drivers, plans]

#### Conclusion
[2-3 sentences on overall performance]

#### References
1. [COMPANY_TICKER] – [Report Name]. [Link]

*Disclaimer: This real-time financial synthesis was dynamically generated by SIHL using proprietary vector analysis of corporate filings. Not financial advice.*

STRICT RULES FOR MODE 2:
1. Use ₹ for all Indian currency values
2. Sentiment must be exactly ONE word: Bullish, Bearish, or Neutral
3. Never add, rename, or remove any section in Mode 2
""".strip()

app = FastAPI(title="SIHL API", version="2.0.0")
ensure_indexes()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def openai_client() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set in backend/.env")
    return OpenAI(api_key=api_key)


def _serialize_report(doc):
    return {
        "company_ticker": doc.get("company_ticker", "UNKNOWN"),
        "company_name": doc.get("company_name", "UNKNOWN"),
        "quarter": doc.get("quarter", "UNKNOWN"),
        "report_type": doc.get("report_type", "UNKNOWN"),
        "original_filename": doc.get("original_filename", ""),
        "total_pages": doc.get("total_pages", 0),
        "total_chunks": doc.get("total_chunks", 0),
        "uploaded_at": doc.get("uploaded_at"),
        "status": doc.get("status", "unknown"),
    }


@app.post("/api/upload")
async def upload_reports(
    files: List[UploadFile] | None = File(default=None),
    files_array: List[UploadFile] | None = File(default=None, alias="files[]"),
):
    all_files = (files or []) + (files_array or [])
    if not all_files:
        raise HTTPException(status_code=400, detail="No PDF files uploaded.")

    response_files = []
    for file in all_files:
        if not file.filename.lower().endswith(".pdf"):
            raise HTTPException(status_code=400, detail=f"{file.filename} is not a PDF file.")
        file_bytes = await file.read()
        try:
            result = ingest_pdf(file_bytes, file.filename)
            response_files.append(
                {
                    "filename": file.filename,
                    "status": "completed",
                    "ticker": result.get("company_ticker", "UNKNOWN"),
                    "quarter": result.get("quarter", "UNKNOWN"),
                    "total_chunks": result.get("total_chunks", 0),
                }
            )
        except Exception as exc:
            response_files.append(
                {
                    "filename": file.filename,
                    "status": "failed",
                    "error": str(exc),
                }
            )

    return {
        "message": f"Processed {len(response_files)} file(s)",
        "files": response_files,
    }


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        chunks = retrieve_relevant_chunks(request.user_message, request.company_ticker, request.quarters)
        chunk_docs = retrieve_chunk_documents(
            request.user_message, request.company_ticker, request.quarters
        )
        user_prompt = (
            "Here is the extracted financial report data:\n\n"
            f"{chunks}\n\n"
            f"User question: {request.user_message}"
        )
        client = openai_client()
        completion = client.chat.completions.create(
            model="gpt-4o",
            max_tokens=4000,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        )
        response_text = (completion.choices[0].message.content or "").strip()
        usage = completion.usage
        tokens_used = (usage.prompt_tokens if usage else 0) + (
            usage.completion_tokens if usage else 0
        )

        _, db = get_database()
        db.chat_history.insert_many(
            [
                {
                    "session_id": request.session_id,
                    "role": "user",
                    "content": request.user_message,
                    "company_ticker": request.company_ticker.upper(),
                    "quarters": request.quarters,
                    "created_at": utc_now(),
                },
                {
                    "session_id": request.session_id,
                    "role": "assistant",
                    "content": response_text,
                    "company_ticker": request.company_ticker.upper(),
                    "quarters": request.quarters,
                    "tokens_used": tokens_used,
                    "created_at": utc_now(),
                },
            ]
        )

        return ChatResponse(
            response=response_text,
            chunks_used=len(chunk_docs),
            tokens_used=tokens_used,
        )
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.post("/api/chat/stream")
async def chat_stream(request: ChatRequest):
    chunks = retrieve_relevant_chunks(request.user_message, request.company_ticker, request.quarters)
    user_prompt = (
        "Here is the extracted financial report data:\n\n"
        f"{chunks}\n\n"
        f"User question: {request.user_message}"
    )
    client = openai_client()

    def event_stream():
        final_text_parts = []
        stream = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            stream=True,
        )
        for event in stream:
            delta = event.choices[0].delta.content if event.choices else None
            if delta:
                final_text_parts.append(delta)
                yield f"data: {json.dumps(delta)}\n\n"
        final_text = "".join(final_text_parts).strip()
        if final_text:
            _, db = get_database()
            db.chat_history.insert_many(
                [
                    {
                        "session_id": request.session_id,
                        "role": "user",
                        "content": request.user_message,
                        "company_ticker": request.company_ticker.upper(),
                        "quarters": request.quarters,
                        "created_at": utc_now(),
                    },
                    {
                        "session_id": request.session_id,
                        "role": "assistant",
                        "content": final_text,
                        "company_ticker": request.company_ticker.upper(),
                        "quarters": request.quarters,
                        "created_at": utc_now(),
                    },
                ]
            )
        yield "data: [DONE]\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


@app.get("/api/reports")
async def get_reports():
    _, db = get_database()
    docs = list(db.reports.find({}, {"_id": 0}).sort("uploaded_at", -1))
    return {"reports": [_serialize_report(doc) for doc in docs]}


@app.get("/api/reports/tickers")
async def get_tickers():
    return {"tickers": get_all_tickers_and_quarters()}


@app.get("/api/reports/{ticker}/{quarter}/status")
async def get_report_status(ticker: str, quarter: str):
    _, db = get_database()
    doc = db.reports.find_one(
        {"company_ticker": ticker.upper(), "quarter": quarter},
        {"_id": 0, "status": 1, "total_chunks": 1},
    )
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")
    return {"status": doc.get("status", "unknown"), "total_chunks": doc.get("total_chunks", 0)}


@app.delete("/api/reports/{ticker}/{quarter}")
async def delete_report(ticker: str, quarter: str):
    _, db = get_database()
    doc = db.reports.find_one({"company_ticker": ticker.upper(), "quarter": quarter})
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")

    db.extracted_json.delete_many({"report_id": doc["_id"]})
    db.embeddings.delete_many({"report_id": doc["_id"]})
    if doc.get("gridfs_file_id"):
        fs = get_gridfs(db)
        try:
            fs.delete(doc["gridfs_file_id"])
        except Exception:
            pass
    db.reports.delete_one({"_id": doc["_id"]})
    return {"message": f"Deleted report for {ticker.upper()} {quarter}"}


@app.get("/api/chat/history/{session_id}")
async def get_chat_history(session_id: str):
    _, db = get_database()
    docs = list(
        db.chat_history.find({"session_id": session_id}, {"_id": 0, "role": 1, "content": 1, "created_at": 1}).sort("created_at", 1)
    )
    return {"session_id": session_id, "history": docs}


@app.get("/api/health", response_model=HealthResponse)
async def health():
    _, db = get_database()
    db.command("ping")
    return HealthResponse(status="ok", mongodb="connected", timestamp=utc_now())
