import json
import os
import pathlib
import threading
import logging
from typing import List

from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from openai import OpenAI

load_dotenv()

from database import ensure_indexes, get_database, get_gridfs, utc_now
from ingest import ingest_pdf, ingest_pdf_path
from models import ChatRequest, ChatResponse, HealthResponse
from retrieval import get_all_tickers_and_quarters, retrieve_chunk_documents, retrieve_relevant_chunks

SYSTEM_PROMPT = """
You are an elite financial research assistant for Indian stock market investors on the SIHL platform.

You have TWO modes of answering. Always choose the most appropriate one based on the user's question.

=========================================
SENTIMENT SCORING RULES (apply in BOTH modes)
=========================================
To determine Sentiment, score the data objectively:
  BULLISH signals (+1 each): revenue growth YoY, PAT/profit growth, margin expansion, debt reduction,
    dividend increase, volume growth, capacity expansion, positive guidance, market share gain.
  BEARISH signals (-1 each): revenue decline, PAT/profit decline or loss, margin compression,
    debt increase, impairment/restructuring charge, negative guidance, significant write-off.

Final score → Bullish (net positive), Bearish (net negative), Neutral (exactly balanced or insufficient data).
NEVER default to Neutral unless the data is genuinely 50/50. Most reports are clearly one direction.

=========================================
MODE 1: DIRECT Q&A (Specific Questions)
=========================================
Use this mode if the user asks a specific, narrow question (e.g., "What is the PAT?", "Compare revenue", "What are the risks?").
- Answer ONLY the specific question asked. Do not generate a full report.
- Begin with "**Sentiment:** [Bullish/Bearish/Neutral]" — apply the scoring rules above rigorously.
- If numeric data is relevant, ALWAYS present it in a clean Markdown table.
- Base answers strictly on the retrieved report chunks.

=========================================
MODE 2: FULL REPORT GENERATION
=========================================
Use this mode if the user asks for a summary, full report, earnings analysis, or general overview.

IMPORTANT: If chunks from MULTIPLE years/periods are provided (e.g. FY21, FY22, FY23, FY24, FY25),
your report MUST cover ALL of them — build a multi-year financial table showing every year as a column.
Do NOT skip or ignore any period that has data in the context.

Respond in EXACTLY this format:

➤ [COMPANY_TICKER] – [Report Type] Report ([Period range, e.g. FY21–FY25])

**Sentiment**
[Bullish / Bearish / Neutral — determined by the scoring rules above, NOT by default]

**Positive Highlights**
- [concise point with year reference, max 15 words]
- [concise point with year reference, max 15 words]
- [concise point with year reference, max 15 words]

**Negative Highlights**
- [concise point with year reference, max 15 words]
- [concise point with year reference, max 15 words]

**Summary**
### Company Financial Report

#### Financial Performance
[Markdown table with one column per fiscal year (FY21 / FY22 / FY23 / FY24 / FY25) for every available metric.
Show actual numbers from the data — do NOT leave cells blank. Add a 'Trend' column at the end summarising direction.]

#### Segment Highlights
- [bullet points covering business segments (e.g., steel, automotive, infrastructure) with year references]

#### Operational Highlights
- [bullet points covering production, utilization, costs, capacity, efficiency metrics — cite year where relevant]

#### Risks and Challenges
- [bullet points]

#### Outlook
- [bullet points on growth drivers, plans]

#### Conclusion
[2-3 sentences summarising the multi-year trajectory]

#### References
1. [COMPANY_TICKER] – [Report Name]

*Disclaimer: This real-time financial synthesis was dynamically generated by SIHL using proprietary vector analysis of corporate filings. Not financial advice.*

STRICT RULES FOR MODE 2:
1. Use ₹ for all Indian currency values
2. Sentiment must be exactly ONE word: Bullish, Bearish, or Neutral
3. Never add, rename, or remove any section in Mode 2
4. If multi-year data is in context, the financial table MUST have all those years as columns
""".strip()

app = FastAPI(title="SIHL API", version="2.0.0")

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s %(levelname)s %(name)s - %(message)s",
)
logger = logging.getLogger("sihl-api")


def _require_admin(request_token: str | None):
    admin_token = (os.getenv("ADMIN_TOKEN") or "").strip()
    if not admin_token:
        raise HTTPException(status_code=503, detail="ADMIN_TOKEN is not configured on the server.")
    if not request_token or request_token != admin_token:
        raise HTTPException(status_code=401, detail="Unauthorized.")

def _cors_origins():
    raw = (os.getenv("CORS_ORIGINS") or "").strip()
    if not raw:
        return ["*"]
    return [o.strip() for o in raw.split(",") if o.strip()]


app.add_middleware(
    CORSMiddleware,
    allow_origins=_cors_origins(),
    allow_credentials=False,  # cannot be True with wildcard origins; keep it cookie-free
    allow_methods=["*"],
    allow_headers=["*"],
)


_startup_lock = threading.Lock()


def _auto_ingest_pdfs_if_needed():
    """
    Production behavior:
    - PDFs are bundled in repo under /pdfs (not user-uploaded).
    - If the DB has no completed reports, ingest PDFs once.
    - Idempotent via SHA-256 hash stored on report docs.
    """
    with _startup_lock:
        _, db = get_database()
        completed_reports = db.reports.count_documents({"status": "completed"})
        if completed_reports > 0:
            logger.info("Startup ingestion skipped: completed reports already exist (%s).", completed_reports)
            return {"status": "skipped", "reason": "reports_exist", "completed_reports": completed_reports}

        pdf_dir = pathlib.Path(__file__).resolve().parent.parent / "pdfs"
        if not pdf_dir.exists():
            logger.warning("Startup ingestion skipped: pdf dir not found: %s", pdf_dir)
            return {"status": "skipped", "reason": "no_pdfs_dir", "pdf_dir": str(pdf_dir)}

        pdf_paths = sorted([p for p in pdf_dir.glob("*.pdf") if p.is_file()])
        if not pdf_paths:
            logger.warning("Startup ingestion skipped: no PDFs found in %s", pdf_dir)
            return {"status": "skipped", "reason": "no_pdfs_found", "pdf_dir": str(pdf_dir)}

        logger.info("Startup ingestion: found %s PDFs in %s", len(pdf_paths), pdf_dir)
        ingested = 0
        skipped = 0
        failed: list[dict] = []
        for p in pdf_paths:
            try:
                result = ingest_pdf_path(str(p))
                if result.get("skipped"):
                    skipped += 1
                else:
                    ingested += 1
            except Exception as exc:
                failed.append({"file": p.name, "error": str(exc)})
                logger.exception("Startup ingestion failed for %s", p.name)
        logger.info("Startup ingestion finished: ingested=%s skipped=%s failed=%s", ingested, skipped, len(failed))
        return {"status": "completed", "ingested": ingested, "skipped": skipped, "failed": failed}


def _start_ingest_in_background():
    def _runner():
        try:
            _auto_ingest_pdfs_if_needed()
        except Exception:
            logger.exception("Ingestion crashed unexpectedly.")

    threading.Thread(target=_runner, name="auto-ingest", daemon=True).start()


@app.post("/api/admin/ingest")
async def admin_ingest(token: str | None = None):
    """Start PDF ingestion in background (free-tier safe)."""
    _require_admin(token)
    _start_ingest_in_background()
    return {"status": "started"}


@app.on_event("startup")
async def _startup():
    ensure_indexes()
    # Critical for Render free tier:
    # - Bind the port fast so health checks pass
    # - Run ingestion in a background thread (best-effort)
    auto_ingest = (os.getenv("AUTO_INGEST_ON_STARTUP", "1") or "1").strip().lower() not in {"0", "false", "no"}
    if not auto_ingest:
        logger.info("Startup ingestion disabled via AUTO_INGEST_ON_STARTUP=0")
        return

    _start_ingest_in_background()


def openai_client() -> OpenAI:
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is not set in backend/.env")
    return OpenAI(api_key=api_key)


def _serialize_report(doc):
    return {
        "company_ticker": doc.get("company_ticker", "UNKNOWN"),
        "company_name": doc.get("company_name", "UNKNOWN"),
        "quarter": doc.get("quarter", "UNKNOWN"),
        "report_type": doc.get("report_type", "UNKNOWN"),
        "original_filename": doc.get("original_filename", ""),
        "total_pages": doc.get("total_pages", 0),
        "total_chunks": doc.get("total_chunks", 0),
        "uploaded_at": doc.get("uploaded_at"),
        "status": doc.get("status", "unknown"),
        "last_processed_page": doc.get("last_processed_page", 0),
        "error": doc.get("error"),
    }


def _extract_section_snippet(chunk_text: str) -> str:
    for line in (chunk_text or "").splitlines():
        cleaned = " ".join(line.strip().split())
        if len(cleaned) >= 8:
            return cleaned[:140]
    return "General financial disclosure"


def _build_source_references(chunk_docs: List[dict]) -> List[str]:
    if not chunk_docs:
        return []

    _, db = get_database()
    report_ids = list({doc.get("report_id") for doc in chunk_docs if doc.get("report_id") is not None})
    report_name_map = {}
    if report_ids:
        for report in db.reports.find({"_id": {"$in": report_ids}}, {"original_filename": 1}):
            report_name_map[report["_id"]] = report.get("original_filename") or "Unknown PDF"

    unique_refs = []
    seen = set()
    for doc in chunk_docs:
        report_id = doc.get("report_id")
        filename = (
            doc.get("source_filename")
            or report_name_map.get(report_id)
            or "Unknown PDF"
        )
        page = doc.get("page_number") or "?"
        section = _extract_section_snippet(doc.get("chunk_text", ""))
        key = (filename, page, section)
        if key in seen:
            continue
        seen.add(key)
        unique_refs.append(f"{filename} | Page {page} | Section: {section}")
        if len(unique_refs) >= 8:
            break

    return unique_refs


@app.post("/api/upload")
async def upload_reports(
    files: List[UploadFile] | None = File(default=None),
    files_array: List[UploadFile] | None = File(default=None, alias="files[]"),
):
    all_files = (files or []) + (files_array or [])
    if not all_files:
        raise HTTPException(status_code=400, detail="No PDF files uploaded.")

    response_files = []
    for file in all_files:
        if not file.filename.lower().endswith(".pdf"):
            raise HTTPException(status_code=400, detail=f"{file.filename} is not a PDF file.")
        file_bytes = await file.read()
        try:
            result = ingest_pdf(file_bytes, file.filename)
            response_files.append(
                {
                    "filename": file.filename,
                    "status": "completed",
                    "ticker": result.get("company_ticker", "UNKNOWN"),
                    "quarter": result.get("quarter", "UNKNOWN"),
                    "total_chunks": result.get("total_chunks", 0),
                }
            )
        except Exception as exc:
            response_files.append(
                {
                    "filename": file.filename,
                    "status": "failed",
                    "error": str(exc),
                }
            )

    return {
        "message": f"Processed {len(response_files)} file(s)",
        "files": response_files,
    }


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    try:
        chunks = retrieve_relevant_chunks(request.user_message, request.company_ticker, request.quarters)
        chunk_docs = retrieve_chunk_documents(
            request.user_message, request.company_ticker, request.quarters
        )
        user_prompt = (
            "Here is the extracted financial report data:\n\n"
            f"{chunks}\n\n"
            f"User question: {request.user_message}"
        )
        client = openai_client()
        completion = client.chat.completions.create(
            model="gpt-4o",
            max_tokens=4000,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        )
        response_text = (completion.choices[0].message.content or "").strip()
        source_refs = _build_source_references(chunk_docs)
        if source_refs:
            reference_block = "\n".join(f"{idx}. {ref}" for idx, ref in enumerate(source_refs, start=1))
            response_text = f"{response_text}\n\n### Source References\n{reference_block}"
        usage = completion.usage
        tokens_used = (usage.prompt_tokens if usage else 0) + (
            usage.completion_tokens if usage else 0
        )

        _, db = get_database()
        db.chat_history.insert_many(
            [
                {
                    "session_id": request.session_id,
                    "role": "user",
                    "content": request.user_message,
                    "company_ticker": request.company_ticker.upper(),
                    "quarters": request.quarters,
                    "created_at": utc_now(),
                },
                {
                    "session_id": request.session_id,
                    "role": "assistant",
                    "content": response_text,
                    "company_ticker": request.company_ticker.upper(),
                    "quarters": request.quarters,
                    "tokens_used": tokens_used,
                    "created_at": utc_now(),
                },
            ]
        )

        return ChatResponse(
            response=response_text,
            chunks_used=len(chunk_docs),
            tokens_used=tokens_used,
        )
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc


@app.post("/api/chat/stream")
async def chat_stream(request: ChatRequest):
    try:
        chunks = retrieve_relevant_chunks(request.user_message, request.company_ticker, request.quarters)
        chunk_docs = retrieve_chunk_documents(request.user_message, request.company_ticker, request.quarters)
    except ValueError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    source_refs = _build_source_references(chunk_docs)
    user_prompt = (
        "Here is the extracted financial report data:\n\n"
        f"{chunks}\n\n"
        f"User question: {request.user_message}"
    )
    client = openai_client()

    def event_stream():
        final_text_parts = []
        stream = client.chat.completions.create(
            model="gpt-4o",
            max_tokens=6000,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            stream=True,
        )
        for event in stream:
            delta = event.choices[0].delta.content if event.choices else None
            if delta:
                final_text_parts.append(delta)
                yield f"data: {json.dumps(delta)}\n\n"
        final_text = "".join(final_text_parts).strip()
        if final_text and source_refs:
            reference_block = "\n".join(f"{idx}. {ref}" for idx, ref in enumerate(source_refs, start=1))
            final_text = f"{final_text}\n\n### Source References\n{reference_block}"
            yield f"data: {json.dumps(f'\n\n### Source References\n{reference_block}')}\n\n"
        if final_text:
            _, db = get_database()
            db.chat_history.insert_many(
                [
                    {
                        "session_id": request.session_id,
                        "role": "user",
                        "content": request.user_message,
                        "company_ticker": request.company_ticker.upper(),
                        "quarters": request.quarters,
                        "created_at": utc_now(),
                    },
                    {
                        "session_id": request.session_id,
                        "role": "assistant",
                        "content": final_text,
                        "company_ticker": request.company_ticker.upper(),
                        "quarters": request.quarters,
                        "created_at": utc_now(),
                    },
                ]
            )
        yield "data: [DONE]\n\n"

    return StreamingResponse(event_stream(), media_type="text/event-stream")


@app.get("/api/reports")
async def get_reports():
    _, db = get_database()
    docs = list(db.reports.find({}, {"_id": 0}).sort("uploaded_at", -1))
    return {"reports": [_serialize_report(doc) for doc in docs]}


@app.get("/api/reports/tickers")
async def get_tickers():
    return {"tickers": get_all_tickers_and_quarters()}


@app.get("/api/reports/{ticker}/{quarter}/status")
async def get_report_status(ticker: str, quarter: str):
    _, db = get_database()
    doc = db.reports.find_one(
        {"company_ticker": ticker.upper(), "quarter": quarter},
        {"_id": 0, "status": 1, "total_chunks": 1},
    )
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")
    return {"status": doc.get("status", "unknown"), "total_chunks": doc.get("total_chunks", 0)}


@app.delete("/api/reports/{ticker}/{quarter}")
async def delete_report(ticker: str, quarter: str):
    _, db = get_database()
    doc = db.reports.find_one({"company_ticker": ticker.upper(), "quarter": quarter})
    if not doc:
        raise HTTPException(status_code=404, detail="Report not found.")

    db.extracted_json.delete_many({"report_id": doc["_id"]})
    db.embeddings.delete_many({"report_id": doc["_id"]})
    if doc.get("gridfs_file_id"):
        fs = get_gridfs(db)
        try:
            fs.delete(doc["gridfs_file_id"])
        except Exception:
            pass
    db.reports.delete_one({"_id": doc["_id"]})
    return {"message": f"Deleted report for {ticker.upper()} {quarter}"}


@app.get("/api/chat/history/{session_id}")
async def get_chat_history(session_id: str):
    _, db = get_database()
    docs = list(
        db.chat_history.find({"session_id": session_id}, {"_id": 0, "role": 1, "content": 1, "created_at": 1}).sort("created_at", 1)
    )
    return {"session_id": session_id, "history": docs}


@app.get("/api/health", response_model=HealthResponse)
async def health():
    _, db = get_database()
    db.command("ping")
    return HealthResponse(status="ok", mongodb="connected", timestamp=utc_now())


@app.post("/api/admin/purge")
async def admin_purge(token: str | None = None, mode: str = "failed_only"):
    """
    Emergency endpoint for free-tier Atlas quota issues.
    mode:
      - failed_only: deletes only failed/processing reports and associated chunks (safe)
      - all: deletes all reports, chunks, embeddings, and GridFS files (dangerous but resets quota fast)
    """
    _require_admin(token)
    _, db = get_database()

    if mode not in {"failed_only", "all"}:
        raise HTTPException(status_code=400, detail="mode must be failed_only or all")

    deleted = {"reports": 0, "embeddings": 0, "extracted_json": 0, "gridfs_files": 0, "gridfs_chunks": 0}

    if mode == "failed_only":
        cursor = db.reports.find({"status": {"$in": ["failed", "processing"]}}, {"_id": 1, "gridfs_file_id": 1})
        report_ids = []
        gridfs_ids = []
        for r in cursor:
            report_ids.append(r["_id"])
            if r.get("gridfs_file_id"):
                gridfs_ids.append(r["gridfs_file_id"])
        if report_ids:
            deleted["embeddings"] = db.embeddings.delete_many({"report_id": {"$in": report_ids}}).deleted_count
            deleted["extracted_json"] = db.extracted_json.delete_many({"report_id": {"$in": report_ids}}).deleted_count
            deleted["reports"] = db.reports.delete_many({"_id": {"$in": report_ids}}).deleted_count
        if gridfs_ids:
            deleted["gridfs_files"] = db["fs.files"].delete_many({"_id": {"$in": gridfs_ids}}).deleted_count
            deleted["gridfs_chunks"] = db["fs.chunks"].delete_many({"files_id": {"$in": gridfs_ids}}).deleted_count
        return {"status": "ok", "mode": mode, "deleted": deleted}

    # mode == "all"
    deleted["embeddings"] = db.embeddings.delete_many({}).deleted_count
    deleted["extracted_json"] = db.extracted_json.delete_many({}).deleted_count
    deleted["reports"] = db.reports.delete_many({}).deleted_count
    deleted["gridfs_files"] = db["fs.files"].delete_many({}).deleted_count
    deleted["gridfs_chunks"] = db["fs.chunks"].delete_many({}).deleted_count
    return {"status": "ok", "mode": mode, "deleted": deleted}
